/*******************************************************************************
 * DIGIT-TSL - Trusted List Manager
 * Copyright (C) 2018 European Commission, provided under the CEF E-Signature programme
 *  
 * This file is part of the "DIGIT-TSL - Trusted List Manager" project.
 *  
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *  
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.tslx;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the eu.europa.esig.jaxb.v5.tslx
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MimeType_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "MimeType");
    private final static QName _X509CertificateLocation_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "X509CertificateLocation");
    private final static QName _PublicKeyLocation_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "PublicKeyLocation");
    private final static QName _ExtendedKeyUsage_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "ExtendedKeyUsage");
    private final static QName _TakenOverBy_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "TakenOverBy");
    private final static QName _CertSubjectDNAttribute_QNAME = new QName("http://uri.etsi.org/02231/v2/additionaltypes#", "CertSubjectDNAttribute");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.esig.jaxb.v5.tslx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtendedKeyUsageTypeV5 }
     * 
     */
    public ExtendedKeyUsageTypeV5 createExtendedKeyUsageTypeV5() {
        return new ExtendedKeyUsageTypeV5();
    }

    /**
     * Create an instance of {@link TakenOverByTypeV5 }
     * 
     */
    public TakenOverByTypeV5 createTakenOverByTypeV5() {
        return new TakenOverByTypeV5();
    }

    /**
     * Create an instance of {@link CertSubjectDNAttributeTypeV5 }
     * 
     */
    public CertSubjectDNAttributeTypeV5 createCertSubjectDNAttributeTypeV5() {
        return new CertSubjectDNAttributeTypeV5();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02231/v2/additionaltypes#", name = "MimeType")
    public JAXBElement<String> createMimeType(String value) {
        return new JAXBElement<String>(_MimeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02231/v2/additionaltypes#", name = "X509CertificateLocation")
    public JAXBElement<String> createX509CertificateLocation(String value) {
        return new JAXBElement<String>(_X509CertificateLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02231/v2/additionaltypes#", name = "PublicKeyLocation")
    public JAXBElement<String> createPublicKeyLocation(String value) {
        return new JAXBElement<String>(_PublicKeyLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedKeyUsageTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02231/v2/additionaltypes#", name = "ExtendedKeyUsage")
    public JAXBElement<ExtendedKeyUsageTypeV5> createExtendedKeyUsage(ExtendedKeyUsageTypeV5 value) {
        return new JAXBElement<ExtendedKeyUsageTypeV5>(_ExtendedKeyUsage_QNAME, ExtendedKeyUsageTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TakenOverByTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02231/v2/additionaltypes#", name = "TakenOverBy")
    public JAXBElement<TakenOverByTypeV5> createTakenOverBy(TakenOverByTypeV5 value) {
        return new JAXBElement<TakenOverByTypeV5>(_TakenOverBy_QNAME, TakenOverByTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertSubjectDNAttributeTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/02231/v2/additionaltypes#", name = "CertSubjectDNAttribute")
    public JAXBElement<CertSubjectDNAttributeTypeV5> createCertSubjectDNAttribute(CertSubjectDNAttributeTypeV5 value) {
        return new JAXBElement<CertSubjectDNAttributeTypeV5>(_CertSubjectDNAttribute_QNAME, CertSubjectDNAttributeTypeV5.class, null, value);
    }

}
