/*******************************************************************************
 * DIGIT-TSL - Trusted List Manager
 * Copyright (C) 2018 European Commission, provided under the CEF E-Signature programme
 *  
 * This file is part of the "DIGIT-TSL - Trusted List Manager" project.
 *  
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *  
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.tslx;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.europa.esig.jaxb.v5.tsl.AnyTypeV5;
import eu.europa.esig.jaxb.v5.tsl.InternationalNamesTypeV5;
import eu.europa.esig.jaxb.v5.tsl.NonEmptyMultiLangURITypeV5;

/**
 * <p>
 * Java class for TakenOverByType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TakenOverByType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="URI" type="{http://uri.etsi.org/02231/v2#}NonEmptyMultiLangURIType"/&gt;
 *         &lt;element name="TSPName" type="{http://uri.etsi.org/02231/v2#}InternationalNamesType"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}SchemeOperatorName"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}SchemeTerritory"/&gt;
 *         &lt;element name="OtherQualifier" type="{http://uri.etsi.org/02231/v2#}AnyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TakenOverByType", propOrder = { "uri", "tspName", "schemeOperatorName", "schemeTerritory", "otherQualifier" })
public class TakenOverByTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "URI", required = true)
    protected NonEmptyMultiLangURITypeV5 uri;
    @XmlElement(name = "TSPName", required = true)
    protected InternationalNamesTypeV5 tspName;
    @XmlElement(name = "SchemeOperatorName", namespace = "http://uri.etsi.org/02231/v2#", required = true)
    protected InternationalNamesTypeV5 schemeOperatorName;
    @XmlElement(name = "SchemeTerritory", namespace = "http://uri.etsi.org/02231/v2#", required = true)
    protected String schemeTerritory;
    @XmlElement(name = "OtherQualifier")
    protected List<AnyTypeV5> otherQualifier;

    /**
     * Gets the value of the uri property.
     * 
     * @return possible object is {@link NonEmptyMultiLangURITypeV5 }
     * 
     */
    public NonEmptyMultiLangURITypeV5 getURI() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *            allowed object is {@link NonEmptyMultiLangURITypeV5 }
     * 
     */
    public void setURI(NonEmptyMultiLangURITypeV5 value) {
        this.uri = value;
    }

    /**
     * Gets the value of the tspName property.
     * 
     * @return possible object is {@link InternationalNamesTypeV5 }
     * 
     */
    public InternationalNamesTypeV5 getTSPName() {
        return tspName;
    }

    /**
     * Sets the value of the tspName property.
     * 
     * @param value
     *            allowed object is {@link InternationalNamesTypeV5 }
     * 
     */
    public void setTSPName(InternationalNamesTypeV5 value) {
        this.tspName = value;
    }

    /**
     * Gets the value of the schemeOperatorName property.
     * 
     * @return possible object is {@link InternationalNamesTypeV5 }
     * 
     */
    public InternationalNamesTypeV5 getSchemeOperatorName() {
        return schemeOperatorName;
    }

    /**
     * Sets the value of the schemeOperatorName property.
     * 
     * @param value
     *            allowed object is {@link InternationalNamesTypeV5 }
     * 
     */
    public void setSchemeOperatorName(InternationalNamesTypeV5 value) {
        this.schemeOperatorName = value;
    }

    /**
     * Gets the value of the schemeTerritory property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSchemeTerritory() {
        return schemeTerritory;
    }

    /**
     * Sets the value of the schemeTerritory property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSchemeTerritory(String value) {
        this.schemeTerritory = value;
    }

    /**
     * Gets the value of the otherQualifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
     * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the otherQualifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOtherQualifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link AnyTypeV5 }
     * 
     * 
     */
    public List<AnyTypeV5> getOtherQualifier() {
        if (otherQualifier == null) {
            otherQualifier = new ArrayList<AnyTypeV5>();
        }
        return this.otherQualifier;
    }

}
