/*******************************************************************************
 * DIGIT-TSL - Trusted List Manager
 * Copyright (C) 2018 European Commission, provided under the CEF E-Signature programme
 *  
 * This file is part of the "DIGIT-TSL - Trusted List Manager" project.
 *  
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *  
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.ecc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the eu.europa.esig.jaxb.v5.ecc
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Qualifications_QNAME = new QName("http://uri.etsi.org/TrstSvc/SvcInfoExt/eSigDir-1999-93-EC-TrustedList/#", "Qualifications");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.esig.jaxb.v5.ecc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QualificationsTypeV5 }
     * 
     */
    public QualificationsTypeV5 createQualificationsTypeV5() {
        return new QualificationsTypeV5();
    }

    /**
     * Create an instance of {@link QualificationElementTypeV5 }
     * 
     */
    public QualificationElementTypeV5 createQualificationElementTypeV5() {
        return new QualificationElementTypeV5();
    }

    /**
     * Create an instance of {@link CriteriaListTypeV5 }
     * 
     */
    public CriteriaListTypeV5 createCriteriaListTypeV5() {
        return new CriteriaListTypeV5();
    }

    /**
     * Create an instance of {@link QualifiersTypeV5 }
     * 
     */
    public QualifiersTypeV5 createQualifiersTypeV5() {
        return new QualifiersTypeV5();
    }

    /**
     * Create an instance of {@link QualifierTypeV5 }
     * 
     */
    public QualifierTypeV5 createQualifierTypeV5() {
        return new QualifierTypeV5();
    }

    /**
     * Create an instance of {@link PoliciesListTypeV5 }
     * 
     */
    public PoliciesListTypeV5 createPoliciesListTypeV5() {
        return new PoliciesListTypeV5();
    }

    /**
     * Create an instance of {@link KeyUsageTypeV5 }
     * 
     */
    public KeyUsageTypeV5 createKeyUsageTypeV5() {
        return new KeyUsageTypeV5();
    }

    /**
     * Create an instance of {@link KeyUsageBitTypeV5 }
     * 
     */
    public KeyUsageBitTypeV5 createKeyUsageBitTypeV5() {
        return new KeyUsageBitTypeV5();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualificationsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/TrstSvc/SvcInfoExt/eSigDir-1999-93-EC-TrustedList/#", name = "Qualifications")
    public JAXBElement<QualificationsTypeV5> createQualifications(QualificationsTypeV5 value) {
        return new JAXBElement<QualificationsTypeV5>(_Qualifications_QNAME, QualificationsTypeV5.class, null, value);
    }

}
