/*******************************************************************************
 * DIGIT-TSL - Trusted List Manager
 * Copyright (C) 2018 European Commission, provided under the CEF E-Signature programme
 *  
 * This file is part of the "DIGIT-TSL - Trusted List Manager" project.
 *  
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *  
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.xades;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the eu.europa.esig.jaxb.v5.xades
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Any_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Any");
    private final static QName _ObjectIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ObjectIdentifier");
    private final static QName _EncapsulatedPKIData_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedPKIData");
    private final static QName _Include_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Include");
    private final static QName _ReferenceInfo_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ReferenceInfo");
    private final static QName _XAdESTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "XAdESTimeStamp");
    private final static QName _OtherTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherTimeStamp");
    private final static QName _QualifyingProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingProperties");
    private final static QName _SignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedProperties");
    private final static QName _UnsignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedProperties");
    private final static QName _SignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedSignatureProperties");
    private final static QName _SignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedDataObjectProperties");
    private final static QName _UnsignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedSignatureProperties");
    private final static QName _UnsignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedDataObjectProperties");
    private final static QName _QualifyingPropertiesReference_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingPropertiesReference");
    private final static QName _SigningTime_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningTime");
    private final static QName _SigningCertificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningCertificate");
    private final static QName _SignaturePolicyIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignaturePolicyIdentifier");
    private final static QName _SPURI_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPURI");
    private final static QName _SPUserNotice_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPUserNotice");
    private final static QName _CounterSignature_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CounterSignature");
    private final static QName _DataObjectFormat_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "DataObjectFormat");
    private final static QName _CommitmentTypeIndication_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CommitmentTypeIndication");
    private final static QName _SignatureProductionPlace_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureProductionPlace");
    private final static QName _SignerRole_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignerRole");
    private final static QName _AllDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AllDataObjectsTimeStamp");
    private final static QName _IndividualDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "IndividualDataObjectsTimeStamp");
    private final static QName _SignatureTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureTimeStamp");
    private final static QName _CompleteCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteCertificateRefs");
    private final static QName _CompleteRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteRevocationRefs");
    private final static QName _AttributeCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeCertificateRefs");
    private final static QName _AttributeRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationRefs");
    private final static QName _SigAndRefsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigAndRefsTimeStamp");
    private final static QName _RefsOnlyTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RefsOnlyTimeStamp");
    private final static QName _CertificateValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertificateValues");
    private final static QName _RevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RevocationValues");
    private final static QName _AttrAuthoritiesCertValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttrAuthoritiesCertValues");
    private final static QName _AttributeRevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationValues");
    private final static QName _ArchiveTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ArchiveTimeStamp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.esig.jaxb.v5.xades
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnyTypeV5 }
     * 
     */
    public AnyTypeV5 createAnyTypeV5() {
        return new AnyTypeV5();
    }

    /**
     * Create an instance of {@link ObjectIdentifierTypeV5 }
     * 
     */
    public ObjectIdentifierTypeV5 createObjectIdentifierTypeV5() {
        return new ObjectIdentifierTypeV5();
    }

    /**
     * Create an instance of {@link EncapsulatedPKIDataTypeV5 }
     * 
     */
    public EncapsulatedPKIDataTypeV5 createEncapsulatedPKIDataTypeV5() {
        return new EncapsulatedPKIDataTypeV5();
    }

    /**
     * Create an instance of {@link IncludeTypeV5 }
     * 
     */
    public IncludeTypeV5 createIncludeTypeV5() {
        return new IncludeTypeV5();
    }

    /**
     * Create an instance of {@link ReferenceInfoTypeV5 }
     * 
     */
    public ReferenceInfoTypeV5 createReferenceInfoTypeV5() {
        return new ReferenceInfoTypeV5();
    }

    /**
     * Create an instance of {@link XAdESTimeStampTypeV5 }
     * 
     */
    public XAdESTimeStampTypeV5 createXAdESTimeStampTypeV5() {
        return new XAdESTimeStampTypeV5();
    }

    /**
     * Create an instance of {@link OtherTimeStampTypeV5 }
     * 
     */
    public OtherTimeStampTypeV5 createOtherTimeStampTypeV5() {
        return new OtherTimeStampTypeV5();
    }

    /**
     * Create an instance of {@link QualifyingPropertiesTypeV5 }
     * 
     */
    public QualifyingPropertiesTypeV5 createQualifyingPropertiesTypeV5() {
        return new QualifyingPropertiesTypeV5();
    }

    /**
     * Create an instance of {@link SignedPropertiesTypeV5 }
     * 
     */
    public SignedPropertiesTypeV5 createSignedPropertiesTypeV5() {
        return new SignedPropertiesTypeV5();
    }

    /**
     * Create an instance of {@link UnsignedPropertiesTypeV5 }
     * 
     */
    public UnsignedPropertiesTypeV5 createUnsignedPropertiesTypeV5() {
        return new UnsignedPropertiesTypeV5();
    }

    /**
     * Create an instance of {@link SignedSignaturePropertiesTypeV5 }
     * 
     */
    public SignedSignaturePropertiesTypeV5 createSignedSignaturePropertiesTypeV5() {
        return new SignedSignaturePropertiesTypeV5();
    }

    /**
     * Create an instance of {@link SignedDataObjectPropertiesTypeV5 }
     * 
     */
    public SignedDataObjectPropertiesTypeV5 createSignedDataObjectPropertiesTypeV5() {
        return new SignedDataObjectPropertiesTypeV5();
    }

    /**
     * Create an instance of {@link UnsignedSignaturePropertiesTypeV5 }
     * 
     */
    public UnsignedSignaturePropertiesTypeV5 createUnsignedSignaturePropertiesTypeV5() {
        return new UnsignedSignaturePropertiesTypeV5();
    }

    /**
     * Create an instance of {@link UnsignedDataObjectPropertiesTypeV5 }
     * 
     */
    public UnsignedDataObjectPropertiesTypeV5 createUnsignedDataObjectPropertiesTypeV5() {
        return new UnsignedDataObjectPropertiesTypeV5();
    }

    /**
     * Create an instance of {@link QualifyingPropertiesReferenceTypeV5 }
     * 
     */
    public QualifyingPropertiesReferenceTypeV5 createQualifyingPropertiesReferenceTypeV5() {
        return new QualifyingPropertiesReferenceTypeV5();
    }

    /**
     * Create an instance of {@link CertIDListTypeV5 }
     * 
     */
    public CertIDListTypeV5 createCertIDListTypeV5() {
        return new CertIDListTypeV5();
    }

    /**
     * Create an instance of {@link SignaturePolicyIdentifierTypeV5 }
     * 
     */
    public SignaturePolicyIdentifierTypeV5 createSignaturePolicyIdentifierTypeV5() {
        return new SignaturePolicyIdentifierTypeV5();
    }

    /**
     * Create an instance of {@link SPUserNoticeTypeV5 }
     * 
     */
    public SPUserNoticeTypeV5 createSPUserNoticeTypeV5() {
        return new SPUserNoticeTypeV5();
    }

    /**
     * Create an instance of {@link CounterSignatureTypeV5 }
     * 
     */
    public CounterSignatureTypeV5 createCounterSignatureTypeV5() {
        return new CounterSignatureTypeV5();
    }

    /**
     * Create an instance of {@link DataObjectFormatTypeV5 }
     * 
     */
    public DataObjectFormatTypeV5 createDataObjectFormatTypeV5() {
        return new DataObjectFormatTypeV5();
    }

    /**
     * Create an instance of {@link CommitmentTypeIndicationTypeV5 }
     * 
     */
    public CommitmentTypeIndicationTypeV5 createCommitmentTypeIndicationTypeV5() {
        return new CommitmentTypeIndicationTypeV5();
    }

    /**
     * Create an instance of {@link SignatureProductionPlaceTypeV5 }
     * 
     */
    public SignatureProductionPlaceTypeV5 createSignatureProductionPlaceTypeV5() {
        return new SignatureProductionPlaceTypeV5();
    }

    /**
     * Create an instance of {@link SignerRoleTypeV5 }
     * 
     */
    public SignerRoleTypeV5 createSignerRoleTypeV5() {
        return new SignerRoleTypeV5();
    }

    /**
     * Create an instance of {@link CompleteCertificateRefsTypeV5 }
     * 
     */
    public CompleteCertificateRefsTypeV5 createCompleteCertificateRefsTypeV5() {
        return new CompleteCertificateRefsTypeV5();
    }

    /**
     * Create an instance of {@link CompleteRevocationRefsTypeV5 }
     * 
     */
    public CompleteRevocationRefsTypeV5 createCompleteRevocationRefsTypeV5() {
        return new CompleteRevocationRefsTypeV5();
    }

    /**
     * Create an instance of {@link CertificateValuesTypeV5 }
     * 
     */
    public CertificateValuesTypeV5 createCertificateValuesTypeV5() {
        return new CertificateValuesTypeV5();
    }

    /**
     * Create an instance of {@link RevocationValuesTypeV5 }
     * 
     */
    public RevocationValuesTypeV5 createRevocationValuesTypeV5() {
        return new RevocationValuesTypeV5();
    }

    /**
     * Create an instance of {@link IdentifierTypeV5 }
     * 
     */
    public IdentifierTypeV5 createIdentifierTypeV5() {
        return new IdentifierTypeV5();
    }

    /**
     * Create an instance of {@link DocumentationReferencesTypeV5 }
     * 
     */
    public DocumentationReferencesTypeV5 createDocumentationReferencesTypeV5() {
        return new DocumentationReferencesTypeV5();
    }

    /**
     * Create an instance of {@link CertIDTypeV5 }
     * 
     */
    public CertIDTypeV5 createCertIDTypeV5() {
        return new CertIDTypeV5();
    }

    /**
     * Create an instance of {@link DigestAlgAndValueTypeV5 }
     * 
     */
    public DigestAlgAndValueTypeV5 createDigestAlgAndValueTypeV5() {
        return new DigestAlgAndValueTypeV5();
    }

    /**
     * Create an instance of {@link SignaturePolicyIdTypeV5 }
     * 
     */
    public SignaturePolicyIdTypeV5 createSignaturePolicyIdTypeV5() {
        return new SignaturePolicyIdTypeV5();
    }

    /**
     * Create an instance of {@link SigPolicyQualifiersListTypeV5 }
     * 
     */
    public SigPolicyQualifiersListTypeV5 createSigPolicyQualifiersListTypeV5() {
        return new SigPolicyQualifiersListTypeV5();
    }

    /**
     * Create an instance of {@link NoticeReferenceTypeV5 }
     * 
     */
    public NoticeReferenceTypeV5 createNoticeReferenceTypeV5() {
        return new NoticeReferenceTypeV5();
    }

    /**
     * Create an instance of {@link IntegerListTypeV5 }
     * 
     */
    public IntegerListTypeV5 createIntegerListTypeV5() {
        return new IntegerListTypeV5();
    }

    /**
     * Create an instance of {@link CommitmentTypeQualifiersListTypeV5 }
     * 
     */
    public CommitmentTypeQualifiersListTypeV5 createCommitmentTypeQualifiersListTypeV5() {
        return new CommitmentTypeQualifiersListTypeV5();
    }

    /**
     * Create an instance of {@link ClaimedRolesListTypeV5 }
     * 
     */
    public ClaimedRolesListTypeV5 createClaimedRolesListTypeV5() {
        return new ClaimedRolesListTypeV5();
    }

    /**
     * Create an instance of {@link CertifiedRolesListTypeV5 }
     * 
     */
    public CertifiedRolesListTypeV5 createCertifiedRolesListTypeV5() {
        return new CertifiedRolesListTypeV5();
    }

    /**
     * Create an instance of {@link CRLRefsTypeV5 }
     * 
     */
    public CRLRefsTypeV5 createCRLRefsTypeV5() {
        return new CRLRefsTypeV5();
    }

    /**
     * Create an instance of {@link CRLRefTypeV5 }
     * 
     */
    public CRLRefTypeV5 createCRLRefTypeV5() {
        return new CRLRefTypeV5();
    }

    /**
     * Create an instance of {@link CRLIdentifierTypeV5 }
     * 
     */
    public CRLIdentifierTypeV5 createCRLIdentifierTypeV5() {
        return new CRLIdentifierTypeV5();
    }

    /**
     * Create an instance of {@link OCSPRefsTypeV5 }
     * 
     */
    public OCSPRefsTypeV5 createOCSPRefsTypeV5() {
        return new OCSPRefsTypeV5();
    }

    /**
     * Create an instance of {@link OCSPRefTypeV5 }
     * 
     */
    public OCSPRefTypeV5 createOCSPRefTypeV5() {
        return new OCSPRefTypeV5();
    }

    /**
     * Create an instance of {@link ResponderIDTypeV5 }
     * 
     */
    public ResponderIDTypeV5 createResponderIDTypeV5() {
        return new ResponderIDTypeV5();
    }

    /**
     * Create an instance of {@link OCSPIdentifierTypeV5 }
     * 
     */
    public OCSPIdentifierTypeV5 createOCSPIdentifierTypeV5() {
        return new OCSPIdentifierTypeV5();
    }

    /**
     * Create an instance of {@link OtherCertStatusRefsTypeV5 }
     * 
     */
    public OtherCertStatusRefsTypeV5 createOtherCertStatusRefsTypeV5() {
        return new OtherCertStatusRefsTypeV5();
    }

    /**
     * Create an instance of {@link CRLValuesTypeV5 }
     * 
     */
    public CRLValuesTypeV5 createCRLValuesTypeV5() {
        return new CRLValuesTypeV5();
    }

    /**
     * Create an instance of {@link OCSPValuesTypeV5 }
     * 
     */
    public OCSPValuesTypeV5 createOCSPValuesTypeV5() {
        return new OCSPValuesTypeV5();
    }

    /**
     * Create an instance of {@link OtherCertStatusValuesTypeV5 }
     * 
     */
    public OtherCertStatusValuesTypeV5 createOtherCertStatusValuesTypeV5() {
        return new OtherCertStatusValuesTypeV5();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Any")
    public JAXBElement<AnyTypeV5> createAny(AnyTypeV5 value) {
        return new JAXBElement<AnyTypeV5>(_Any_QNAME, AnyTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectIdentifierTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ObjectIdentifier")
    public JAXBElement<ObjectIdentifierTypeV5> createObjectIdentifier(ObjectIdentifierTypeV5 value) {
        return new JAXBElement<ObjectIdentifierTypeV5>(_ObjectIdentifier_QNAME, ObjectIdentifierTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncapsulatedPKIDataTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "EncapsulatedPKIData")
    public JAXBElement<EncapsulatedPKIDataTypeV5> createEncapsulatedPKIData(EncapsulatedPKIDataTypeV5 value) {
        return new JAXBElement<EncapsulatedPKIDataTypeV5>(_EncapsulatedPKIData_QNAME, EncapsulatedPKIDataTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncludeTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Include")
    public JAXBElement<IncludeTypeV5> createInclude(IncludeTypeV5 value) {
        return new JAXBElement<IncludeTypeV5>(_Include_QNAME, IncludeTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceInfoTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ReferenceInfo")
    public JAXBElement<ReferenceInfoTypeV5> createReferenceInfo(ReferenceInfoTypeV5 value) {
        return new JAXBElement<ReferenceInfoTypeV5>(_ReferenceInfo_QNAME, ReferenceInfoTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "XAdESTimeStamp")
    public JAXBElement<XAdESTimeStampTypeV5> createXAdESTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_XAdESTimeStamp_QNAME, XAdESTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherTimeStamp")
    public JAXBElement<OtherTimeStampTypeV5> createOtherTimeStamp(OtherTimeStampTypeV5 value) {
        return new JAXBElement<OtherTimeStampTypeV5>(_OtherTimeStamp_QNAME, OtherTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifyingPropertiesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "QualifyingProperties")
    public JAXBElement<QualifyingPropertiesTypeV5> createQualifyingProperties(QualifyingPropertiesTypeV5 value) {
        return new JAXBElement<QualifyingPropertiesTypeV5>(_QualifyingProperties_QNAME, QualifyingPropertiesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedPropertiesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedProperties")
    public JAXBElement<SignedPropertiesTypeV5> createSignedProperties(SignedPropertiesTypeV5 value) {
        return new JAXBElement<SignedPropertiesTypeV5>(_SignedProperties_QNAME, SignedPropertiesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsignedPropertiesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedProperties")
    public JAXBElement<UnsignedPropertiesTypeV5> createUnsignedProperties(UnsignedPropertiesTypeV5 value) {
        return new JAXBElement<UnsignedPropertiesTypeV5>(_UnsignedProperties_QNAME, UnsignedPropertiesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedSignaturePropertiesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedSignatureProperties")
    public JAXBElement<SignedSignaturePropertiesTypeV5> createSignedSignatureProperties(SignedSignaturePropertiesTypeV5 value) {
        return new JAXBElement<SignedSignaturePropertiesTypeV5>(_SignedSignatureProperties_QNAME, SignedSignaturePropertiesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedDataObjectPropertiesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedDataObjectProperties")
    public JAXBElement<SignedDataObjectPropertiesTypeV5> createSignedDataObjectProperties(SignedDataObjectPropertiesTypeV5 value) {
        return new JAXBElement<SignedDataObjectPropertiesTypeV5>(_SignedDataObjectProperties_QNAME, SignedDataObjectPropertiesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsignedSignaturePropertiesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedSignatureProperties")
    public JAXBElement<UnsignedSignaturePropertiesTypeV5> createUnsignedSignatureProperties(UnsignedSignaturePropertiesTypeV5 value) {
        return new JAXBElement<UnsignedSignaturePropertiesTypeV5>(_UnsignedSignatureProperties_QNAME, UnsignedSignaturePropertiesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsignedDataObjectPropertiesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedDataObjectProperties")
    public JAXBElement<UnsignedDataObjectPropertiesTypeV5> createUnsignedDataObjectProperties(UnsignedDataObjectPropertiesTypeV5 value) {
        return new JAXBElement<UnsignedDataObjectPropertiesTypeV5>(_UnsignedDataObjectProperties_QNAME, UnsignedDataObjectPropertiesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifyingPropertiesReferenceTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "QualifyingPropertiesReference")
    public JAXBElement<QualifyingPropertiesReferenceTypeV5> createQualifyingPropertiesReference(QualifyingPropertiesReferenceTypeV5 value) {
        return new JAXBElement<QualifyingPropertiesReferenceTypeV5>(_QualifyingPropertiesReference_QNAME, QualifyingPropertiesReferenceTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigningTime")
    public JAXBElement<XMLGregorianCalendar> createSigningTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SigningTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertIDListTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigningCertificate")
    public JAXBElement<CertIDListTypeV5> createSigningCertificate(CertIDListTypeV5 value) {
        return new JAXBElement<CertIDListTypeV5>(_SigningCertificate_QNAME, CertIDListTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePolicyIdentifierTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignaturePolicyIdentifier")
    public JAXBElement<SignaturePolicyIdentifierTypeV5> createSignaturePolicyIdentifier(SignaturePolicyIdentifierTypeV5 value) {
        return new JAXBElement<SignaturePolicyIdentifierTypeV5>(_SignaturePolicyIdentifier_QNAME, SignaturePolicyIdentifierTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SPURI")
    public JAXBElement<String> createSPURI(String value) {
        return new JAXBElement<String>(_SPURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPUserNoticeTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SPUserNotice")
    public JAXBElement<SPUserNoticeTypeV5> createSPUserNotice(SPUserNoticeTypeV5 value) {
        return new JAXBElement<SPUserNoticeTypeV5>(_SPUserNotice_QNAME, SPUserNoticeTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CounterSignatureTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CounterSignature")
    public JAXBElement<CounterSignatureTypeV5> createCounterSignature(CounterSignatureTypeV5 value) {
        return new JAXBElement<CounterSignatureTypeV5>(_CounterSignature_QNAME, CounterSignatureTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectFormatTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "DataObjectFormat")
    public JAXBElement<DataObjectFormatTypeV5> createDataObjectFormat(DataObjectFormatTypeV5 value) {
        return new JAXBElement<DataObjectFormatTypeV5>(_DataObjectFormat_QNAME, DataObjectFormatTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommitmentTypeIndicationTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CommitmentTypeIndication")
    public JAXBElement<CommitmentTypeIndicationTypeV5> createCommitmentTypeIndication(CommitmentTypeIndicationTypeV5 value) {
        return new JAXBElement<CommitmentTypeIndicationTypeV5>(_CommitmentTypeIndication_QNAME, CommitmentTypeIndicationTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureProductionPlaceTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureProductionPlace")
    public JAXBElement<SignatureProductionPlaceTypeV5> createSignatureProductionPlace(SignatureProductionPlaceTypeV5 value) {
        return new JAXBElement<SignatureProductionPlaceTypeV5>(_SignatureProductionPlace_QNAME, SignatureProductionPlaceTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignerRoleTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignerRole")
    public JAXBElement<SignerRoleTypeV5> createSignerRole(SignerRoleTypeV5 value) {
        return new JAXBElement<SignerRoleTypeV5>(_SignerRole_QNAME, SignerRoleTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AllDataObjectsTimeStamp")
    public JAXBElement<XAdESTimeStampTypeV5> createAllDataObjectsTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_AllDataObjectsTimeStamp_QNAME, XAdESTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "IndividualDataObjectsTimeStamp")
    public JAXBElement<XAdESTimeStampTypeV5> createIndividualDataObjectsTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_IndividualDataObjectsTimeStamp_QNAME, XAdESTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureTimeStamp")
    public JAXBElement<XAdESTimeStampTypeV5> createSignatureTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_SignatureTimeStamp_QNAME, XAdESTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteCertificateRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteCertificateRefs")
    public JAXBElement<CompleteCertificateRefsTypeV5> createCompleteCertificateRefs(CompleteCertificateRefsTypeV5 value) {
        return new JAXBElement<CompleteCertificateRefsTypeV5>(_CompleteCertificateRefs_QNAME, CompleteCertificateRefsTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteRevocationRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteRevocationRefs")
    public JAXBElement<CompleteRevocationRefsTypeV5> createCompleteRevocationRefs(CompleteRevocationRefsTypeV5 value) {
        return new JAXBElement<CompleteRevocationRefsTypeV5>(_CompleteRevocationRefs_QNAME, CompleteRevocationRefsTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteCertificateRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeCertificateRefs")
    public JAXBElement<CompleteCertificateRefsTypeV5> createAttributeCertificateRefs(CompleteCertificateRefsTypeV5 value) {
        return new JAXBElement<CompleteCertificateRefsTypeV5>(_AttributeCertificateRefs_QNAME, CompleteCertificateRefsTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteRevocationRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationRefs")
    public JAXBElement<CompleteRevocationRefsTypeV5> createAttributeRevocationRefs(CompleteRevocationRefsTypeV5 value) {
        return new JAXBElement<CompleteRevocationRefsTypeV5>(_AttributeRevocationRefs_QNAME, CompleteRevocationRefsTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigAndRefsTimeStamp")
    public JAXBElement<XAdESTimeStampTypeV5> createSigAndRefsTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_SigAndRefsTimeStamp_QNAME, XAdESTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RefsOnlyTimeStamp")
    public JAXBElement<XAdESTimeStampTypeV5> createRefsOnlyTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_RefsOnlyTimeStamp_QNAME, XAdESTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertificateValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertificateValues")
    public JAXBElement<CertificateValuesTypeV5> createCertificateValues(CertificateValuesTypeV5 value) {
        return new JAXBElement<CertificateValuesTypeV5>(_CertificateValues_QNAME, CertificateValuesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevocationValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RevocationValues")
    public JAXBElement<RevocationValuesTypeV5> createRevocationValues(RevocationValuesTypeV5 value) {
        return new JAXBElement<RevocationValuesTypeV5>(_RevocationValues_QNAME, RevocationValuesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertificateValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttrAuthoritiesCertValues")
    public JAXBElement<CertificateValuesTypeV5> createAttrAuthoritiesCertValues(CertificateValuesTypeV5 value) {
        return new JAXBElement<CertificateValuesTypeV5>(_AttrAuthoritiesCertValues_QNAME, CertificateValuesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevocationValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationValues")
    public JAXBElement<RevocationValuesTypeV5> createAttributeRevocationValues(RevocationValuesTypeV5 value) {
        return new JAXBElement<RevocationValuesTypeV5>(_AttributeRevocationValues_QNAME, RevocationValuesTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ArchiveTimeStamp")
    public JAXBElement<XAdESTimeStampTypeV5> createArchiveTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_ArchiveTimeStamp_QNAME, XAdESTimeStampTypeV5.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CounterSignatureTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CounterSignature", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<CounterSignatureTypeV5> createUnsignedSignaturePropertiesTypeV5CounterSignature(CounterSignatureTypeV5 value) {
        return new JAXBElement<CounterSignatureTypeV5>(_CounterSignature_QNAME, CounterSignatureTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureTimeStamp", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<XAdESTimeStampTypeV5> createUnsignedSignaturePropertiesTypeV5SignatureTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_SignatureTimeStamp_QNAME, XAdESTimeStampTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteCertificateRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteCertificateRefs", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<CompleteCertificateRefsTypeV5> createUnsignedSignaturePropertiesTypeV5CompleteCertificateRefs(CompleteCertificateRefsTypeV5 value) {
        return new JAXBElement<CompleteCertificateRefsTypeV5>(_CompleteCertificateRefs_QNAME, CompleteCertificateRefsTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteRevocationRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteRevocationRefs", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<CompleteRevocationRefsTypeV5> createUnsignedSignaturePropertiesTypeV5CompleteRevocationRefs(CompleteRevocationRefsTypeV5 value) {
        return new JAXBElement<CompleteRevocationRefsTypeV5>(_CompleteRevocationRefs_QNAME, CompleteRevocationRefsTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteCertificateRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeCertificateRefs", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<CompleteCertificateRefsTypeV5> createUnsignedSignaturePropertiesTypeV5AttributeCertificateRefs(CompleteCertificateRefsTypeV5 value) {
        return new JAXBElement<CompleteCertificateRefsTypeV5>(_AttributeCertificateRefs_QNAME, CompleteCertificateRefsTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteRevocationRefsTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationRefs", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<CompleteRevocationRefsTypeV5> createUnsignedSignaturePropertiesTypeV5AttributeRevocationRefs(CompleteRevocationRefsTypeV5 value) {
        return new JAXBElement<CompleteRevocationRefsTypeV5>(_AttributeRevocationRefs_QNAME, CompleteRevocationRefsTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigAndRefsTimeStamp", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<XAdESTimeStampTypeV5> createUnsignedSignaturePropertiesTypeV5SigAndRefsTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_SigAndRefsTimeStamp_QNAME, XAdESTimeStampTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RefsOnlyTimeStamp", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<XAdESTimeStampTypeV5> createUnsignedSignaturePropertiesTypeV5RefsOnlyTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_RefsOnlyTimeStamp_QNAME, XAdESTimeStampTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertificateValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertificateValues", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<CertificateValuesTypeV5> createUnsignedSignaturePropertiesTypeV5CertificateValues(CertificateValuesTypeV5 value) {
        return new JAXBElement<CertificateValuesTypeV5>(_CertificateValues_QNAME, CertificateValuesTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevocationValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RevocationValues", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<RevocationValuesTypeV5> createUnsignedSignaturePropertiesTypeV5RevocationValues(RevocationValuesTypeV5 value) {
        return new JAXBElement<RevocationValuesTypeV5>(_RevocationValues_QNAME, RevocationValuesTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertificateValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttrAuthoritiesCertValues", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<CertificateValuesTypeV5> createUnsignedSignaturePropertiesTypeV5AttrAuthoritiesCertValues(CertificateValuesTypeV5 value) {
        return new JAXBElement<CertificateValuesTypeV5>(_AttrAuthoritiesCertValues_QNAME, CertificateValuesTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevocationValuesTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationValues", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<RevocationValuesTypeV5> createUnsignedSignaturePropertiesTypeV5AttributeRevocationValues(RevocationValuesTypeV5 value) {
        return new JAXBElement<RevocationValuesTypeV5>(_AttributeRevocationValues_QNAME, RevocationValuesTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStampTypeV5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ArchiveTimeStamp", scope = UnsignedSignaturePropertiesTypeV5.class)
    public JAXBElement<XAdESTimeStampTypeV5> createUnsignedSignaturePropertiesTypeV5ArchiveTimeStamp(XAdESTimeStampTypeV5 value) {
        return new JAXBElement<XAdESTimeStampTypeV5>(_ArchiveTimeStamp_QNAME, XAdESTimeStampTypeV5.class, UnsignedSignaturePropertiesTypeV5.class, value);
    }

}
