/*******************************************************************************
 * DIGIT-TSL - Trusted List Manager non-EU
 * Copyright (C) 2018 European Commission, provided under the CEF E-Signature programme
 *  
 * This file is part of the "DIGIT-TSL - Trusted List Manager non-EU" project.
 *  
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *  
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 ******************************************************************************/
package eu.europa.ec.joinup.tsl.model.enums;

public enum CheckName {

    // LANGUAGE
    IS_ATTRIBUTE_LANG_PRESENT, IS_ATTRIBUTE_LANG_LOWERCASE, IS_ATTRIBUTE_LANG_ALLOWED, IS_LIST_CONTAIN_LANG_EN,
    
    // URI
    IS_URIS_VALID, IS_URIS_ACCESSIBLE,

    // POSTAL ADDRESSES
    IS_POSTAL_ADDRESSES_PRESENT, IS_POSTAL_ADDRESSES_STREET_NOT_EMPTY, IS_POSTAL_ADDRESSES_LOCALITY_NOT_EMPTY, IS_POSTAL_ADDRESSES_COUNTRY_NOT_EMPTY, IS_POSTAL_ADDRESSES_COUNTRY_ALLOWED,
    
    // DIGITAL IDENTITY
    IS_VALID_CERTIFICATE, IS_SUBJECT_NAME_MATCH, IS_X509SKI_MATCH, IS_CERTIFICATE_EXPIRED,

    // SCHEME INFORMATION
    IS_TSL_TAG_PRESENT, IS_TSL_TAG_CORRECT, IS_ELECTRONIC_ADDRESS_PRESENT, IS_SCHEME_NAME_PRESENT, IS_INFORMATION_URI_PRESENT, IS_POSTAL_ADDRESS_PRESENT, 
    IS_TL_TYPE_PRESENT, IS_ISSUE_DATE_PRESENT,  IS_STATUS_DETERMINATION_PRESENT, IS_COMMUNITY_RULES_PRESENT, IS_OPERATOR_NAME_PRESENT,
    IS_SEQUENCE_NUMBER_GREATER_THAN_ZERO, IS_HISTORICAL_INFORMATION_PERIOD_CORRECT, IS_SCHEME_NAME_START_WITH_COUNTRY_CODE, IS_TL_TYPE_CORRECT, IS_STATUS_DETERMINATION_CORRECT, 
    IS_COMMUNITY_RULES_CORRECT,
     
    // POINTERS
    IS_MIME_TYPE_PRESENT, IS_MIME_TYPE_CORRECT, IS_LOCATION_PRESENT, IS_DIGITAL_IDENTITIES_CORRECT, IS_TERRITORY_PRESENT, IS_TERRITORY_CORRECT,
    
    // TSP SERVICE PROVIDER
    IS_TSP_NAME_PRESENT, IS_TSP_TRADE_NAME_PRESENT,
    
    // SERVICES
    IS_SERVICE_TYPE_ID_PRESENT, IS_X509CERTIFICATE_ORGANIZATION_MATCH, IS_QUALIFIER_URI_CORRECT_VALUE, IS_SERVICE_EXTENSION_ASI_ALLOWED, IS_SERVICE_EXTENSION_ASI_SIG_SEAL_ALLOWED, 
    IS_QUALIFICATION_EXTENSION_ALLOWED, IS_EXPIRED_CERT_REVOC_INFO_EXTENSION_ALLOWED, IS_SERVICE_DEFINITION_URI_PRESENT_FOR_NATIONAL_ROOT_CA_QC,
    IS_SERVICE_STATUS_PRESENT, IS_SERVICE_STATUS_CORRECT, IS_SERVICE_STATUS_STARTING_TIME_PRESENT, IS_SERVICE_NAME_PRESENT, IS_DIGITAL_IDENTITIES_PRESENT,  IS_SERVICE_STATUS_STARTING_TIME_ORDER, IS_SERVICE_AND_HISTORY_HAVE_SAME_TYPE_IDENTIFIER, 
    IS_SERVICE_AND_HISTORY_HAVE_SAME_SUBJECT_NAME, IS_SERVICE_AND_HISTORY_HAVE_SAME_X509SKI, IS_SERVICE_TYPE_ID_CORRECT,

    // DATE
    IS_ISSUE_DATE_IN_THE_PAST, IS_NEXT_UPDATE_PRESENT, IS_NEXT_UPDATE_IN_THE_FUTURE, IS_NEXT_UPDATE_MAX_6_MONTHS_AFTER_ISSUE_DATE
}
