/*******************************************************************************
 * DIGIT-TSL - Trusted List Manager
 * Copyright (C) 2018 European Commission, provided under the CEF E-Signature programme
 *  
 * This file is part of the "DIGIT-TSL - Trusted List Manager" project.
 *  
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 *  
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.tsl;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TSLSchemeInformationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSLSchemeInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TSLVersionIdentifier" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="TSLSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}TSLType"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}SchemeOperatorName"/&gt;
 *         &lt;element name="SchemeOperatorAddress" type="{http://uri.etsi.org/02231/v2#}AddressType"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}SchemeName"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}SchemeInformationURI"/&gt;
 *         &lt;element name="StatusDeterminationApproach" type="{http://uri.etsi.org/02231/v2#}NonEmptyURIType"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}SchemeTypeCommunityRules" minOccurs="0"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}SchemeTerritory" minOccurs="0"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}PolicyOrLegalNotice" minOccurs="0"/&gt;
 *         &lt;element name="HistoricalInformationPeriod" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}PointersToOtherTSL" minOccurs="0"/&gt;
 *         &lt;element name="ListIssueDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}NextUpdate"/&gt;
 *         &lt;element ref="{http://uri.etsi.org/02231/v2#}DistributionPoints" minOccurs="0"/&gt;
 *         &lt;element name="SchemeExtensions" type="{http://uri.etsi.org/02231/v2#}ExtensionsListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSLSchemeInformationType", propOrder = { "tslVersionIdentifier", "tslSequenceNumber", "tslType", "schemeOperatorName", "schemeOperatorAddress", "schemeName", "schemeInformationURI",
        "statusDeterminationApproach", "schemeTypeCommunityRules", "schemeTerritory", "policyOrLegalNotice", "historicalInformationPeriod", "pointersToOtherTSL", "listIssueDateTime", "nextUpdate",
        "distributionPoints", "schemeExtensions" })
public class TSLSchemeInformationTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TSLVersionIdentifier", required = true)
    protected BigInteger tslVersionIdentifier;
    @XmlElement(name = "TSLSequenceNumber", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger tslSequenceNumber;
    @XmlElement(name = "TSLType", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String tslType;
    @XmlElement(name = "SchemeOperatorName", required = true)
    protected InternationalNamesTypeV5 schemeOperatorName;
    @XmlElement(name = "SchemeOperatorAddress", required = true)
    protected AddressTypeV5 schemeOperatorAddress;
    @XmlElement(name = "SchemeName", required = true)
    protected InternationalNamesTypeV5 schemeName;
    @XmlElement(name = "SchemeInformationURI", required = true)
    protected NonEmptyMultiLangURIListTypeV5 schemeInformationURI;
    @XmlElement(name = "StatusDeterminationApproach", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String statusDeterminationApproach;
    @XmlElement(name = "SchemeTypeCommunityRules")
    protected NonEmptyMultiLangURIListTypeV5 schemeTypeCommunityRules;
    @XmlElement(name = "SchemeTerritory")
    protected String schemeTerritory;
    @XmlElement(name = "PolicyOrLegalNotice")
    protected PolicyOrLegalnoticeTypeV5 policyOrLegalNotice;
    @XmlElement(name = "HistoricalInformationPeriod", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger historicalInformationPeriod;
    @XmlElement(name = "PointersToOtherTSL")
    protected OtherTSLPointersTypeV5 pointersToOtherTSL;
    @XmlElement(name = "ListIssueDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar listIssueDateTime;
    @XmlElement(name = "NextUpdate", required = true)
    protected NextUpdateTypeV5 nextUpdate;
    @XmlElement(name = "DistributionPoints")
    protected NonEmptyURIListTypeV5 distributionPoints;
    @XmlElement(name = "SchemeExtensions")
    protected ExtensionsListTypeV5 schemeExtensions;

    /**
     * Gets the value of the tslVersionIdentifier property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTSLVersionIdentifier() {
        return tslVersionIdentifier;
    }

    /**
     * Sets the value of the tslVersionIdentifier property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setTSLVersionIdentifier(BigInteger value) {
        this.tslVersionIdentifier = value;
    }

    /**
     * Gets the value of the tslSequenceNumber property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTSLSequenceNumber() {
        return tslSequenceNumber;
    }

    /**
     * Sets the value of the tslSequenceNumber property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setTSLSequenceNumber(BigInteger value) {
        this.tslSequenceNumber = value;
    }

    /**
     * Gets the value of the tslType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTSLType() {
        return tslType;
    }

    /**
     * Sets the value of the tslType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTSLType(String value) {
        this.tslType = value;
    }

    /**
     * Gets the value of the schemeOperatorName property.
     * 
     * @return possible object is {@link InternationalNamesTypeV5 }
     * 
     */
    public InternationalNamesTypeV5 getSchemeOperatorName() {
        return schemeOperatorName;
    }

    /**
     * Sets the value of the schemeOperatorName property.
     * 
     * @param value
     *            allowed object is {@link InternationalNamesTypeV5 }
     * 
     */
    public void setSchemeOperatorName(InternationalNamesTypeV5 value) {
        this.schemeOperatorName = value;
    }

    /**
     * Gets the value of the schemeOperatorAddress property.
     * 
     * @return possible object is {@link AddressTypeV5 }
     * 
     */
    public AddressTypeV5 getSchemeOperatorAddress() {
        return schemeOperatorAddress;
    }

    /**
     * Sets the value of the schemeOperatorAddress property.
     * 
     * @param value
     *            allowed object is {@link AddressTypeV5 }
     * 
     */
    public void setSchemeOperatorAddress(AddressTypeV5 value) {
        this.schemeOperatorAddress = value;
    }

    /**
     * Gets the value of the schemeName property.
     * 
     * @return possible object is {@link InternationalNamesTypeV5 }
     * 
     */
    public InternationalNamesTypeV5 getSchemeName() {
        return schemeName;
    }

    /**
     * Sets the value of the schemeName property.
     * 
     * @param value
     *            allowed object is {@link InternationalNamesTypeV5 }
     * 
     */
    public void setSchemeName(InternationalNamesTypeV5 value) {
        this.schemeName = value;
    }

    /**
     * Gets the value of the schemeInformationURI property.
     * 
     * @return possible object is {@link NonEmptyMultiLangURIListTypeV5 }
     * 
     */
    public NonEmptyMultiLangURIListTypeV5 getSchemeInformationURI() {
        return schemeInformationURI;
    }

    /**
     * Sets the value of the schemeInformationURI property.
     * 
     * @param value
     *            allowed object is {@link NonEmptyMultiLangURIListTypeV5 }
     * 
     */
    public void setSchemeInformationURI(NonEmptyMultiLangURIListTypeV5 value) {
        this.schemeInformationURI = value;
    }

    /**
     * Gets the value of the statusDeterminationApproach property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatusDeterminationApproach() {
        return statusDeterminationApproach;
    }

    /**
     * Sets the value of the statusDeterminationApproach property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStatusDeterminationApproach(String value) {
        this.statusDeterminationApproach = value;
    }

    /**
     * Gets the value of the schemeTypeCommunityRules property.
     * 
     * @return possible object is {@link NonEmptyMultiLangURIListTypeV5 }
     * 
     */
    public NonEmptyMultiLangURIListTypeV5 getSchemeTypeCommunityRules() {
        return schemeTypeCommunityRules;
    }

    /**
     * Sets the value of the schemeTypeCommunityRules property.
     * 
     * @param value
     *            allowed object is {@link NonEmptyMultiLangURIListTypeV5 }
     * 
     */
    public void setSchemeTypeCommunityRules(NonEmptyMultiLangURIListTypeV5 value) {
        this.schemeTypeCommunityRules = value;
    }

    /**
     * Gets the value of the schemeTerritory property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSchemeTerritory() {
        return schemeTerritory;
    }

    /**
     * Sets the value of the schemeTerritory property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSchemeTerritory(String value) {
        this.schemeTerritory = value;
    }

    /**
     * Gets the value of the policyOrLegalNotice property.
     * 
     * @return possible object is {@link PolicyOrLegalnoticeTypeV5 }
     * 
     */
    public PolicyOrLegalnoticeTypeV5 getPolicyOrLegalNotice() {
        return policyOrLegalNotice;
    }

    /**
     * Sets the value of the policyOrLegalNotice property.
     * 
     * @param value
     *            allowed object is {@link PolicyOrLegalnoticeTypeV5 }
     * 
     */
    public void setPolicyOrLegalNotice(PolicyOrLegalnoticeTypeV5 value) {
        this.policyOrLegalNotice = value;
    }

    /**
     * Gets the value of the historicalInformationPeriod property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getHistoricalInformationPeriod() {
        return historicalInformationPeriod;
    }

    /**
     * Sets the value of the historicalInformationPeriod property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setHistoricalInformationPeriod(BigInteger value) {
        this.historicalInformationPeriod = value;
    }

    /**
     * Gets the value of the pointersToOtherTSL property.
     * 
     * @return possible object is {@link OtherTSLPointersTypeV5 }
     * 
     */
    public OtherTSLPointersTypeV5 getPointersToOtherTSL() {
        return pointersToOtherTSL;
    }

    /**
     * Sets the value of the pointersToOtherTSL property.
     * 
     * @param value
     *            allowed object is {@link OtherTSLPointersTypeV5 }
     * 
     */
    public void setPointersToOtherTSL(OtherTSLPointersTypeV5 value) {
        this.pointersToOtherTSL = value;
    }

    /**
     * Gets the value of the listIssueDateTime property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getListIssueDateTime() {
        return listIssueDateTime;
    }

    /**
     * Sets the value of the listIssueDateTime property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     * 
     */
    public void setListIssueDateTime(XMLGregorianCalendar value) {
        this.listIssueDateTime = value;
    }

    /**
     * Gets the value of the nextUpdate property.
     * 
     * @return possible object is {@link NextUpdateTypeV5 }
     * 
     */
    public NextUpdateTypeV5 getNextUpdate() {
        return nextUpdate;
    }

    /**
     * Sets the value of the nextUpdate property.
     * 
     * @param value
     *            allowed object is {@link NextUpdateTypeV5 }
     * 
     */
    public void setNextUpdate(NextUpdateTypeV5 value) {
        this.nextUpdate = value;
    }

    /**
     * Gets the value of the distributionPoints property.
     * 
     * @return possible object is {@link NonEmptyURIListTypeV5 }
     * 
     */
    public NonEmptyURIListTypeV5 getDistributionPoints() {
        return distributionPoints;
    }

    /**
     * Sets the value of the distributionPoints property.
     * 
     * @param value
     *            allowed object is {@link NonEmptyURIListTypeV5 }
     * 
     */
    public void setDistributionPoints(NonEmptyURIListTypeV5 value) {
        this.distributionPoints = value;
    }

    /**
     * Gets the value of the schemeExtensions property.
     * 
     * @return possible object is {@link ExtensionsListTypeV5 }
     * 
     */
    public ExtensionsListTypeV5 getSchemeExtensions() {
        return schemeExtensions;
    }

    /**
     * Sets the value of the schemeExtensions property.
     * 
     * @param value
     *            allowed object is {@link ExtensionsListTypeV5 }
     * 
     */
    public void setSchemeExtensions(ExtensionsListTypeV5 value) {
        this.schemeExtensions = value;
    }

}
